[package]
name = "viceroy"
description = "Viceroy is a local testing daemon for Compute@Edge."
version = "0.3.0"
authors = ["Fastly"]
readme = "../README.md"
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://developer.fastly.com/learning/compute/testing/#running-a-local-testing-server"
homepage = "https://developer.fastly.com/learning/compute/"
repository = "https://github.com/fastly/Viceroy"
keywords = ["wasm", "fastly", "compute@edge"]
categories = [
  "command-line-utilities",
  "development-tools",
  "network-programming",
  "simulation",
  "wasm"
]

[[bin]]
name = "viceroy"
path = "src/main.rs"

[dependencies]
itertools = "0.10.0"
structopt = "0.3.21"
tokio = {version = "1.2", features = ["full"]}
viceroy-lib = {path = "../lib", version = "^0.3.0"}
tracing = "0.1.26"
tracing-subscriber = "0.2.19"
tracing-futures = "0.2.5"
hyper = {version = "0.14.0", features = ["full"]}
wat = "1.0.38"
serde_json = "1.0.66"

[dev-dependencies]
anyhow = "1.0.31"
futures = "0.3"
url = "2.2"
